# Generated by Django 2.2.3 on 2019-08-02 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, null=True, verbose_name='Area name')),
                ('expected_controls', models.CharField(max_length=1000, null=True, verbose_name='Expected Controls')),
                ('findings', models.CharField(max_length=1000, null=True, verbose_name='Findings')),
                ('risk', models.CharField(choices=[('High', 'high'), ('Medium', 'medium'), ('Low', 'low')], max_length=50, null=True, verbose_name='Risk Severity')),
                ('recommendation', models.CharField(max_length=1000, null=True, verbose_name='Recommendation')),
                ('comment', models.CharField(max_length=1000, null=True, verbose_name='Management Comment')),
                ('implementation_date', models.DateField(null=True, verbose_name='Target Implementation Date')),
            ],
            options={
                'verbose_name': 'Area',
            },
        ),
        migrations.CreateModel(
            name='BU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bu_name', models.CharField(max_length=100, verbose_name='Unit name')),
            ],
            options={
                'verbose_name': 'Business Unit',
            },
        ),
        migrations.CreateModel(
            name='CO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=100, verbose_name='Country Office Name')),
            ],
            options={
                'verbose_name_plural': 'Country Offices',
                'verbose_name': 'Country Office',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, verbose_name='Section name')),
            ],
            options={
                'verbose_name': 'Section',
            },
        ),
        migrations.AlterModelOptions(
            name='ro',
            options={'verbose_name': 'Regional Office'},
        ),
        migrations.RemoveField(
            model_name='ro',
            name='name',
        ),
        migrations.AddField(
            model_name='ro',
            name='ro_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Regional office name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, verbose_name='Template Title')),
                ('areas', models.ManyToManyField(to='core.Area', verbose_name='Areas')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BU', verbose_name='Business Unit')),
                ('country_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CO', verbose_name='Country Office')),
                ('regional_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RO', verbose_name='Regional Office')),
                ('sections', models.ManyToManyField(to='core.Section', verbose_name='Sections')),
            ],
            options={
                'verbose_name': 'Template',
            },
        ),
        migrations.CreateModel(
            name='Oversight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oversight_name', models.CharField(max_length=100, verbose_name='Oversight Name')),
                ('close_year', models.DateTimeField(null=True, verbose_name='Year')),
                ('status', models.CharField(choices=[('new', 'New'), ('ongoing', 'Ongoing'), ('follow_up', 'Follow Up'), ('closed', 'Closed')], max_length=50, verbose_name='Status')),
                ('areas', models.ManyToManyField(to='core.Area', verbose_name='Areas')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BU', verbose_name='Business Unit')),
                ('country_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CO', verbose_name='Country Office')),
                ('regional_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RO', verbose_name='Regional Office')),
                ('sections', models.ManyToManyField(to='core.Section', verbose_name='Sections')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Oversight',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Section', verbose_name='Section'),
        ),
    ]
