# Generated by Django 2.2.3 on 2019-07-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ro',
            options={'verbose_name': 'Regional Offices'},
        ),
        migrations.AlterField(
            model_name='ro',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Regional office name'),
        ),
    ]
