# Generated by Django 2.2.3 on 2019-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190726_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterModelOptions(
            name='ro',
            options={'verbose_name': 'Regional Office'},
        ),
    ]
