# Generated by Django 2.2.3 on 2019-07-26 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190726_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='BU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Unit name')),
            ],
            options={
                'verbose_name': 'Business Unit',
            },
        ),
        migrations.CreateModel(
            name='MainObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Object name')),
            ],
            options={
                'verbose_name': 'Main Object',
            },
        ),
        migrations.CreateModel(
            name='ManagementComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Management Comment',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Section name')),
            ],
            options={
                'verbose_name': 'Section',
            },
        ),
        migrations.AlterModelOptions(
            name='co',
            options={'verbose_name': 'Country Office', 'verbose_name_plural': 'Country Offices'},
        ),
        migrations.AlterField(
            model_name='co',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Country Office Name'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BU', verbose_name='Business Unit')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ManagementComment', verbose_name='Comments')),
                ('country_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CO', verbose_name='Country Office')),
                ('objects', models.ManyToManyField(to='core.MainObject')),
                ('regional_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RO', verbose_name='Regional Office')),
                ('sections', models.ManyToManyField(to='core.Section')),
            ],
            options={
                'verbose_name': 'Template',
            },
        ),
    ]
