# Generated by Django 2.2.3 on 2019-07-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190726_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='comments',
        ),
        migrations.AddField(
            model_name='template',
            name='comments',
            field=models.ManyToManyField(to='core.ManagementComment'),
        ),
    ]
