# Generated by Django 2.2.3 on 2019-07-26 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190726_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='implementation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
