# Generated by Django 2.2.3 on 2019-07-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_template_implementation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, verbose_name='Area name')),
                ('expected_controls', models.CharField(max_length=500, verbose_name='Expected Controls')),
                ('findings', models.CharField(max_length=100, verbose_name='Findings')),
                ('risk', models.CharField(choices=[('High', 'high'), ('Medium', 'medium'), ('Low', 'low')], max_length=50, verbose_name='Risk Severity')),
                ('recommendation', models.CharField(max_length=500, verbose_name='Recommendation')),
                ('comment', models.CharField(max_length=500, verbose_name='Management Comment')),
                ('implementation_date', models.DateField(verbose_name='Target Implementation Date')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Area',
            },
        ),
        migrations.RemoveField(
            model_name='template',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='template',
            name='implementation_date',
        ),
        migrations.RemoveField(
            model_name='template',
            name='objects',
        ),
        migrations.DeleteModel(
            name='MainObject',
        ),
        migrations.DeleteModel(
            name='ManagementComment',
        ),
        migrations.AddField(
            model_name='template',
            name='areas',
            field=models.ManyToManyField(to='core.Area'),
        ),
    ]
