# Generated by Django 2.2.3 on 2019-07-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190727_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='template',
            field=models.ManyToManyField(to='core.Template', verbose_name='template'),
        ),
    ]
