# Generated by Django 2.2.3 on 2019-07-29 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190728_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='areas',
        ),
        migrations.AddField(
            model_name='area',
            name='mission',
            field=models.ManyToManyField(to='core.Template', verbose_name='Oversight Mission'),
        ),
        migrations.CreateModel(
            name='OversightMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mission Name')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Template', verbose_name='Oversight Mission')),
            ],
        ),
    ]
