# Generated by Django 2.2.3 on 2019-07-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190729_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='mission',
            field=models.ManyToManyField(to='core.OversightMission', verbose_name='Oversight Mission'),
        ),
    ]
