# Generated by Django 2.2.3 on 2019-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190729_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='mission',
        ),
        migrations.AddField(
            model_name='area',
            name='template',
            field=models.ManyToManyField(to='core.Template', verbose_name='Oversight Mission'),
        ),
        migrations.DeleteModel(
            name='OversightMission',
        ),
    ]
