# Generated by Django 2.2.3 on 2019-07-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190729_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bu',
            old_name='name',
            new_name='bu_name',
        ),
        migrations.RenameField(
            model_name='co',
            old_name='name',
            new_name='co_name',
        ),
        migrations.RenameField(
            model_name='ro',
            old_name='name',
            new_name='ro_name',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='section_name',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='name',
            new_name='template_name',
        ),
    ]
