# Generated by Django 2.2.3 on 2019-07-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190730_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Area name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='comment',
            field=models.CharField(max_length=500, null=True, verbose_name='Management Comment'),
        ),
        migrations.AlterField(
            model_name='area',
            name='expected_controls',
            field=models.CharField(max_length=500, null=True, verbose_name='Expected Controls'),
        ),
        migrations.AlterField(
            model_name='area',
            name='findings',
            field=models.CharField(max_length=100, null=True, verbose_name='Findings'),
        ),
        migrations.AlterField(
            model_name='area',
            name='implementation_date',
            field=models.DateField(null=True, verbose_name='Target Implementation Date'),
        ),
        migrations.AlterField(
            model_name='area',
            name='recommendation',
            field=models.CharField(max_length=500, null=True, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='area',
            name='risk',
            field=models.CharField(choices=[('High', 'high'), ('Medium', 'medium'), ('Low', 'low')], max_length=50, null=True, verbose_name='Risk Severity'),
        ),
        migrations.AlterField(
            model_name='area',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='area',
            name='template',
            field=models.ManyToManyField(null=True, to='core.Template', verbose_name='Oversight Mission'),
        ),
    ]
