# Generated by Django 2.2.3 on 2019-07-31 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190730_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='template',
            field=models.ManyToManyField(null=True, to='core.Template', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='OversightReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100, verbose_name='Oversight Report')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Oversight Report',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='oversight',
            field=models.ManyToManyField(null=True, to='core.OversightReport', verbose_name='OVersight Report'),
        ),
        migrations.AddField(
            model_name='section',
            name='oversight',
            field=models.ManyToManyField(null=True, to='core.OversightReport', verbose_name='OVersight Report'),
        ),
    ]
