# Generated by Django 2.2.3 on 2019-07-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190731_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='oversight',
        ),
        migrations.RemoveField(
            model_name='section',
            name='oversight',
        ),
        migrations.AddField(
            model_name='oversightreport',
            name='areas',
            field=models.ManyToManyField(to='core.Area', verbose_name='Areas'),
        ),
        migrations.AddField(
            model_name='oversightreport',
            name='sections',
            field=models.ManyToManyField(to='core.Section', verbose_name='Sections'),
        ),
        migrations.AlterField(
            model_name='oversightreport',
            name='report_name',
            field=models.CharField(max_length=100, verbose_name='Oversight Report Title'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_name',
            field=models.CharField(max_length=100, verbose_name='Template Title'),
        ),
    ]
