# Generated by Django 2.2.3 on 2019-07-31 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190731_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oversightreport',
            name='template',
        ),
        migrations.AddField(
            model_name='oversightreport',
            name='business_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.BU', verbose_name='Business Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oversightreport',
            name='country_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.CO', verbose_name='Country Office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oversightreport',
            name='regional_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.RO', verbose_name='Regional Office'),
            preserve_default=False,
        ),
    ]
