# Generated by Django 2.2.3 on 2019-07-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190731_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='template',
        ),
        migrations.RemoveField(
            model_name='section',
            name='template',
        ),
        migrations.AddField(
            model_name='template',
            name='areas',
            field=models.ManyToManyField(to='core.Area', verbose_name='Areas'),
        ),
        migrations.AddField(
            model_name='template',
            name='oversight_report_name',
            field=models.CharField(default='report name', max_length=100, verbose_name='Oversight Report Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='sections',
            field=models.ManyToManyField(to='core.Section', verbose_name='Sections'),
        ),
    ]
