# Generated by Django 2.2.3 on 2019-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190801_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oversight',
            name='template',
        ),
        migrations.AddField(
            model_name='oversight',
            name='templates',
            field=models.ManyToManyField(null=True, to='core.Template', verbose_name='Template'),
        ),
    ]
