# Generated by Django 2.2.3 on 2019-08-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190801_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oversight',
            old_name='oversight_status',
            new_name='status',
        ),
    ]
