# Generated by Django 2.2.3 on 2019-08-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190801_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oversight',
            name='templates',
        ),
        migrations.AddField(
            model_name='oversight',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Template', verbose_name='Template'),
        ),
    ]
