# Generated by Django 2.2.3 on 2019-08-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190801_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='Management Comment'),
        ),
        migrations.AlterField(
            model_name='area',
            name='expected_controls',
            field=models.CharField(max_length=1000, null=True, verbose_name='Expected Controls'),
        ),
        migrations.AlterField(
            model_name='area',
            name='findings',
            field=models.CharField(max_length=1000, null=True, verbose_name='Findings'),
        ),
        migrations.AlterField(
            model_name='area',
            name='recommendation',
            field=models.CharField(max_length=1000, null=True, verbose_name='Recommendation'),
        ),
    ]
