# Generated by Django 2.2.3 on 2019-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190802_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='risk',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50, null=True, verbose_name='Risk Severity'),
        ),
    ]
